import Foundation

struct PlayerCountry: Codable, Hashable, Identifiable {
    let code: String
    let name: String

    var id: String {
        code.isEmpty ? name : code
    }
}

enum CountryCatalog {
    static let all: [PlayerCountry] = CountryCodePair.all
        .map { pair in
            PlayerCountry(
                code: pair.alpha3,
                name: displayName(for: pair.alpha2, defaultName: pair.alpha3)
            )
        }
        .sorted { left, right in
            left.name.localizedCaseInsensitiveCompare(right.name) == .orderedAscending
        }

    private static let displayLocale = Locale(identifier: "en_US")

    private static func displayName(for alpha2: String, defaultName: String) -> String {
        if alpha2 == "XK" {
            return "Kosovo"
        }

        return displayLocale.localizedString(forRegionCode: alpha2) ?? defaultName
    }
}

private struct CountryCodePair {
    let alpha2: String
    let alpha3: String

    static let all: [CountryCodePair] = [
        .init(alpha2: "AF", alpha3: "AFG"),
        .init(alpha2: "AL", alpha3: "ALB"),
        .init(alpha2: "DZ", alpha3: "DZA"),
        .init(alpha2: "AD", alpha3: "AND"),
        .init(alpha2: "AO", alpha3: "AGO"),
        .init(alpha2: "AG", alpha3: "ATG"),
        .init(alpha2: "AR", alpha3: "ARG"),
        .init(alpha2: "AM", alpha3: "ARM"),
        .init(alpha2: "AU", alpha3: "AUS"),
        .init(alpha2: "AT", alpha3: "AUT"),
        .init(alpha2: "AZ", alpha3: "AZE"),
        .init(alpha2: "BS", alpha3: "BHS"),
        .init(alpha2: "BH", alpha3: "BHR"),
        .init(alpha2: "BD", alpha3: "BGD"),
        .init(alpha2: "BB", alpha3: "BRB"),
        .init(alpha2: "BY", alpha3: "BLR"),
        .init(alpha2: "BE", alpha3: "BEL"),
        .init(alpha2: "BZ", alpha3: "BLZ"),
        .init(alpha2: "BJ", alpha3: "BEN"),
        .init(alpha2: "BT", alpha3: "BTN"),
        .init(alpha2: "BO", alpha3: "BOL"),
        .init(alpha2: "BA", alpha3: "BIH"),
        .init(alpha2: "BW", alpha3: "BWA"),
        .init(alpha2: "BR", alpha3: "BRA"),
        .init(alpha2: "BN", alpha3: "BRN"),
        .init(alpha2: "BG", alpha3: "BGR"),
        .init(alpha2: "BF", alpha3: "BFA"),
        .init(alpha2: "BI", alpha3: "BDI"),
        .init(alpha2: "CV", alpha3: "CPV"),
        .init(alpha2: "KH", alpha3: "KHM"),
        .init(alpha2: "CM", alpha3: "CMR"),
        .init(alpha2: "CA", alpha3: "CAN"),
        .init(alpha2: "CF", alpha3: "CAF"),
        .init(alpha2: "TD", alpha3: "TCD"),
        .init(alpha2: "CL", alpha3: "CHL"),
        .init(alpha2: "CN", alpha3: "CHN"),
        .init(alpha2: "CO", alpha3: "COL"),
        .init(alpha2: "KM", alpha3: "COM"),
        .init(alpha2: "CG", alpha3: "COG"),
        .init(alpha2: "CD", alpha3: "COD"),
        .init(alpha2: "CR", alpha3: "CRI"),
        .init(alpha2: "CI", alpha3: "CIV"),
        .init(alpha2: "HR", alpha3: "HRV"),
        .init(alpha2: "CU", alpha3: "CUB"),
        .init(alpha2: "CY", alpha3: "CYP"),
        .init(alpha2: "CZ", alpha3: "CZE"),
        .init(alpha2: "DK", alpha3: "DNK"),
        .init(alpha2: "DJ", alpha3: "DJI"),
        .init(alpha2: "DM", alpha3: "DMA"),
        .init(alpha2: "DO", alpha3: "DOM"),
        .init(alpha2: "EC", alpha3: "ECU"),
        .init(alpha2: "EG", alpha3: "EGY"),
        .init(alpha2: "SV", alpha3: "SLV"),
        .init(alpha2: "GQ", alpha3: "GNQ"),
        .init(alpha2: "ER", alpha3: "ERI"),
        .init(alpha2: "EE", alpha3: "EST"),
        .init(alpha2: "SZ", alpha3: "SWZ"),
        .init(alpha2: "ET", alpha3: "ETH"),
        .init(alpha2: "FJ", alpha3: "FJI"),
        .init(alpha2: "FI", alpha3: "FIN"),
        .init(alpha2: "FR", alpha3: "FRA"),
        .init(alpha2: "GA", alpha3: "GAB"),
        .init(alpha2: "GM", alpha3: "GMB"),
        .init(alpha2: "GE", alpha3: "GEO"),
        .init(alpha2: "DE", alpha3: "DEU"),
        .init(alpha2: "GH", alpha3: "GHA"),
        .init(alpha2: "GR", alpha3: "GRC"),
        .init(alpha2: "GD", alpha3: "GRD"),
        .init(alpha2: "GT", alpha3: "GTM"),
        .init(alpha2: "GN", alpha3: "GIN"),
        .init(alpha2: "GW", alpha3: "GNB"),
        .init(alpha2: "GY", alpha3: "GUY"),
        .init(alpha2: "HT", alpha3: "HTI"),
        .init(alpha2: "HN", alpha3: "HND"),
        .init(alpha2: "HU", alpha3: "HUN"),
        .init(alpha2: "IS", alpha3: "ISL"),
        .init(alpha2: "IN", alpha3: "IND"),
        .init(alpha2: "ID", alpha3: "IDN"),
        .init(alpha2: "IR", alpha3: "IRN"),
        .init(alpha2: "IQ", alpha3: "IRQ"),
        .init(alpha2: "IE", alpha3: "IRL"),
        .init(alpha2: "IL", alpha3: "ISR"),
        .init(alpha2: "IT", alpha3: "ITA"),
        .init(alpha2: "JM", alpha3: "JAM"),
        .init(alpha2: "JP", alpha3: "JPN"),
        .init(alpha2: "JO", alpha3: "JOR"),
        .init(alpha2: "KZ", alpha3: "KAZ"),
        .init(alpha2: "KE", alpha3: "KEN"),
        .init(alpha2: "KI", alpha3: "KIR"),
        .init(alpha2: "KP", alpha3: "PRK"),
        .init(alpha2: "KR", alpha3: "KOR"),
        .init(alpha2: "KW", alpha3: "KWT"),
        .init(alpha2: "KG", alpha3: "KGZ"),
        .init(alpha2: "LA", alpha3: "LAO"),
        .init(alpha2: "LV", alpha3: "LVA"),
        .init(alpha2: "LB", alpha3: "LBN"),
        .init(alpha2: "LS", alpha3: "LSO"),
        .init(alpha2: "LR", alpha3: "LBR"),
        .init(alpha2: "LY", alpha3: "LBY"),
        .init(alpha2: "LI", alpha3: "LIE"),
        .init(alpha2: "LT", alpha3: "LTU"),
        .init(alpha2: "LU", alpha3: "LUX"),
        .init(alpha2: "MG", alpha3: "MDG"),
        .init(alpha2: "MW", alpha3: "MWI"),
        .init(alpha2: "MY", alpha3: "MYS"),
        .init(alpha2: "MV", alpha3: "MDV"),
        .init(alpha2: "ML", alpha3: "MLI"),
        .init(alpha2: "MT", alpha3: "MLT"),
        .init(alpha2: "MH", alpha3: "MHL"),
        .init(alpha2: "MR", alpha3: "MRT"),
        .init(alpha2: "MU", alpha3: "MUS"),
        .init(alpha2: "MX", alpha3: "MEX"),
        .init(alpha2: "FM", alpha3: "FSM"),
        .init(alpha2: "MD", alpha3: "MDA"),
        .init(alpha2: "MC", alpha3: "MCO"),
        .init(alpha2: "MN", alpha3: "MNG"),
        .init(alpha2: "ME", alpha3: "MNE"),
        .init(alpha2: "MA", alpha3: "MAR"),
        .init(alpha2: "MZ", alpha3: "MOZ"),
        .init(alpha2: "MM", alpha3: "MMR"),
        .init(alpha2: "NA", alpha3: "NAM"),
        .init(alpha2: "NR", alpha3: "NRU"),
        .init(alpha2: "NP", alpha3: "NPL"),
        .init(alpha2: "NL", alpha3: "NLD"),
        .init(alpha2: "NZ", alpha3: "NZL"),
        .init(alpha2: "NI", alpha3: "NIC"),
        .init(alpha2: "NE", alpha3: "NER"),
        .init(alpha2: "NG", alpha3: "NGA"),
        .init(alpha2: "MK", alpha3: "MKD"),
        .init(alpha2: "NO", alpha3: "NOR"),
        .init(alpha2: "OM", alpha3: "OMN"),
        .init(alpha2: "PK", alpha3: "PAK"),
        .init(alpha2: "PW", alpha3: "PLW"),
        .init(alpha2: "PS", alpha3: "PSE"),
        .init(alpha2: "PA", alpha3: "PAN"),
        .init(alpha2: "PG", alpha3: "PNG"),
        .init(alpha2: "PY", alpha3: "PRY"),
        .init(alpha2: "PE", alpha3: "PER"),
        .init(alpha2: "PH", alpha3: "PHL"),
        .init(alpha2: "PL", alpha3: "POL"),
        .init(alpha2: "PT", alpha3: "PRT"),
        .init(alpha2: "QA", alpha3: "QAT"),
        .init(alpha2: "RO", alpha3: "ROU"),
        .init(alpha2: "RU", alpha3: "RUS"),
        .init(alpha2: "RW", alpha3: "RWA"),
        .init(alpha2: "KN", alpha3: "KNA"),
        .init(alpha2: "LC", alpha3: "LCA"),
        .init(alpha2: "VC", alpha3: "VCT"),
        .init(alpha2: "WS", alpha3: "WSM"),
        .init(alpha2: "SM", alpha3: "SMR"),
        .init(alpha2: "ST", alpha3: "STP"),
        .init(alpha2: "SA", alpha3: "SAU"),
        .init(alpha2: "SN", alpha3: "SEN"),
        .init(alpha2: "RS", alpha3: "SRB"),
        .init(alpha2: "SC", alpha3: "SYC"),
        .init(alpha2: "SL", alpha3: "SLE"),
        .init(alpha2: "SG", alpha3: "SGP"),
        .init(alpha2: "SK", alpha3: "SVK"),
        .init(alpha2: "SI", alpha3: "SVN"),
        .init(alpha2: "SB", alpha3: "SLB"),
        .init(alpha2: "SO", alpha3: "SOM"),
        .init(alpha2: "ZA", alpha3: "ZAF"),
        .init(alpha2: "SS", alpha3: "SSD"),
        .init(alpha2: "ES", alpha3: "ESP"),
        .init(alpha2: "LK", alpha3: "LKA"),
        .init(alpha2: "SD", alpha3: "SDN"),
        .init(alpha2: "SR", alpha3: "SUR"),
        .init(alpha2: "SE", alpha3: "SWE"),
        .init(alpha2: "CH", alpha3: "CHE"),
        .init(alpha2: "SY", alpha3: "SYR"),
        .init(alpha2: "TW", alpha3: "TWN"),
        .init(alpha2: "TJ", alpha3: "TJK"),
        .init(alpha2: "TZ", alpha3: "TZA"),
        .init(alpha2: "TH", alpha3: "THA"),
        .init(alpha2: "TL", alpha3: "TLS"),
        .init(alpha2: "TG", alpha3: "TGO"),
        .init(alpha2: "TO", alpha3: "TON"),
        .init(alpha2: "TT", alpha3: "TTO"),
        .init(alpha2: "TN", alpha3: "TUN"),
        .init(alpha2: "TR", alpha3: "TUR"),
        .init(alpha2: "TM", alpha3: "TKM"),
        .init(alpha2: "TV", alpha3: "TUV"),
        .init(alpha2: "UG", alpha3: "UGA"),
        .init(alpha2: "UA", alpha3: "UKR"),
        .init(alpha2: "AE", alpha3: "ARE"),
        .init(alpha2: "GB", alpha3: "GBR"),
        .init(alpha2: "US", alpha3: "USA"),
        .init(alpha2: "UY", alpha3: "URY"),
        .init(alpha2: "UZ", alpha3: "UZB"),
        .init(alpha2: "VU", alpha3: "VUT"),
        .init(alpha2: "VA", alpha3: "VAT"),
        .init(alpha2: "VE", alpha3: "VEN"),
        .init(alpha2: "VN", alpha3: "VNM"),
        .init(alpha2: "YE", alpha3: "YEM"),
        .init(alpha2: "ZM", alpha3: "ZMB"),
        .init(alpha2: "ZW", alpha3: "ZWE"),
        .init(alpha2: "XK", alpha3: "XXK"),
    ]
}
